### ISSUE TITLE
Villager cannot open Door

### ISSUE THREAD

**Issue by ardissaps** [AfraidMonster/metal-doors-1.17.1#4]
![image](https://user-images.githubusercontent.com/82106625/175484807-869e4c43-a649-4fab-b960-5d17f9cec449.png)
1.18.2

**Comment by AfraidMonster** [comment]
Got a fix on the way for this once 1.19.1 releases :)

**Comment by ardissaps** [comment]
> Got a fix on the way for this once 1.19.1 releases :)

Would you post it to 1.18.2 too? :)
my 1.19 pack isn't finished :(

**Comment by AfraidMonster** [comment]
Sure

**Comment by AfraidMonster** [comment]
Files now live on curseforge

**Comment by ardissaps** [comment]
Thank you very much!
